config/routes.rb
App01::Application.routes.draw do

  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/help', to: 'pages#help'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  get '/signup', to: 'users#new'

  resources :sessions, :only => [:new, :create, :destroy]
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'

  resources :microposts, :only => [:create, :destroy]

  resources :relationships, :only => [:create, :destroy]

end

app/models/micropost.rb
# == Schema Information
#
# Table name: microposts
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Micropost < ActiveRecord::Base
	belongs_to :user

	attr_accessible :content

	default_scope :order => 'microposts.created_at DESC'

	validates :content, presence: true, length: 1..140
	validates :user_id, presence: true

	scope :from_users_followed_by, lambda { |user| followed_by(user) }

	private

		def self.followed_by(user)
			followed_ids = %(SELECT followed_id FROM relationships
							 WHERE follower_id = :user_id)
			where("user_id IN (#{followed_ids}) OR user_id = :user_id", :user_id => user)
		end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

	attr_accessible :followed_id

	belongs_to :follower, :foreign_key => "follower_id", :class_name => "User"
	belongs_to :followed, :foreign_key => "followed_id", :class_name => "User"

	validates :follower_id, :presence => true
	validates :followed_id, :presence => true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  has_many :microposts, :dependent => :destroy
  has_many :relationships, :dependent => :destroy, :foreign_key => "follower_id"
  has_many :reverse_relationships, :dependent => :destroy, :foreign_key => "followed_id", :class_name => "Relationship"
  has_many :following, :through => :relationships, :source => :followed
  has_many :followers, :through => :reverse_relationships, :source => :follower

  attr_accessor   :password
  attr_accessible :name, :email, :password, :password_confirmation

	email_regex = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i

	validates :name,	presence: true,
										length: 5..30

	validates :email,	presence: true,
										format: email_regex,
										length: 5..50,
										uniqueness: true
							
	validates :password,	length: 6..20,
												confirmation: true


  before_save :encrypt_password

  def feed
    Micropost.from_users_followed_by(self)
  end

  def following?(followed)
    relationships.find_by_followed_id(followed)
  end

  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end

  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.encrypted_password == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	include ApplicationHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_filter :authenticate

	def create
		@micropost = current_user.microposts.build(params[:micropost])
		if @micropost.save
			redirect_to root_path, :notice => "Post was successfully saved"
		else
			@user = current_user
			flash.now.alert = "Error in saving post"
			@feed_items = current_user.feed.all
			render 'pages/home'
		end
	end

	def destroy
		Micropost.find(params[:id]).destroy
		redirect_to root_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		@user = current_user
		@micropost = Micropost.new
    	@feed_items = current_user.feed
		if @user
			@page_name = "Homepage for #{@user.name}"
		else
			@page_name = "Home"
		end
	end

	def about
		@page_name = "About"
	end

	def contact
		@page_name = "Contact"
	end

	def help
		@page_name = "Help"
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def create
		user = User.find(params[:relationship][:followed_id])
		current_user.follow!(user)
		flash.now.alert = "Followed user"
		redirect_to root_path
	end

	def destroy
		current_user.relationships.find(params[:id]).destroy
		flash.now.alert = "Unfollowed user"
		redirect_to root_path
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @page_name = "Log In"
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to (session[:redirect_to] || user_path(@user.id)), :notice => "Logged In!"
    else
      flash.now.alert = "Invalid email or password"
      @page_name = "Log In"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    session[:redirect_to] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :except => [:show, :new, :create]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin, :only => [:index, :destroy]

  def index
      @users = User.paginate(:page => params[:page])
  end

  def new
    @page_name = "Register"
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, :notice => "Logged in!"
    else
      @page_name = "Register"
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @page_name = @user.name
    @microposts = @user.microposts
  end

  def edit
    @page_name = "Edit your profile"
    @user = User.find(params[:id])
  end

  def update
    @page_name = "Edit your profile"    
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, :notice => "Profile has been updated"
    else
      flash.now.alert = "Profile wasn't updated"
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash.now.alert = "User has been deleted"
    redirect_to users_path
  end

  def following
    @page_name = "Following"
    @follow = current_user.following.all
    render 'follow'
  end

  def followers
    @page_name = "Followers"
    @follow = current_user.followers.all
    render 'follow'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def authenticate
    session[:redirect_to] = request.fullpath
    redirect_to signin_path, :notice => "Please, sign in" unless current_user
  end

  def correct_user
  	@user = User.find(params[:id])
  	redirect_to root_path unless @user == current_user
  end

  def admin
    redirect_to root_path unless current_user.admin?
  end
end

app/helpers/pages_helper.rb
module PagesHelper

	def site_title
		base_title = "App 01"

		if @page_name.nil?
			base_title
		else
			"#{base_title} | #{@page_name}"
		end 
	end
	
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_debug.html.erb
<div class="part rounded_box">
	<%= debug(params) if Rails.env.development? %>
</div>

app/views/layouts/_flash_errors.html.erb
<% flash.each do |key, value| %>
 <p><%= value %></p>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer rounded_box">
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>
</div>

app/views/layouts/_header.html.erb
<div class="header">
	<div class="logo rounded_box"><%= link_to "APP 01", root_path %></div>
	
	<div class="menu rounded_box">
		<%= link_to "Home", root_path %>
		<%= link_to "Help", help_path %>
		<% if current_user %>
			<%= link_to "Users", users_path if current_user.admin? %>
			<%= link_to "Profile", current_user %>
			<%= link_to "Sign Out", signout_path %>
		<% else %>
			<%= link_to "Sign In", signin_path %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= site_title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<% if current_user %>
	<div class="part rounded_box align-right">Logged in as <%= current_user.name %></div>
<% else %>
	<div class="part"><%= link_to("Sign Up Here", signup_path, :class => 'button') %></div>
<% end %>

<div class="part"><%= render 'layouts/flash_errors' %></div>

<div class="container rounded_box">
	<%= yield %>
</div>

<%= render 'layouts/footer' %>

<!-- <%= render 'layouts/debug' %> -->

</body>
</html>

app/views/pages/about.html.erb
About page

app/views/pages/contact.html.erb
Contact page

app/views/pages/help.html.erb
Help page

app/views/pages/home.html.erb
<% if current_user %>

	<p>Name: <%= @user.name %><br>
	Microposts: <%= @user.microposts.count %><br>
	<%= link_to 'Edit My Profile', edit_user_path(@user) %><br>
	<%= link_to "#{@user.following.count} following", following_user_path(@user) %><br>
	<%= link_to pluralize(@user.followers.count, "follower"), followers_user_path(@user) %></p>
	<hr>
	<h1>Create a new post</h1>
	<%= form_for @micropost do |m| %>
		<p>Text: <br><%= m.text_area :content %></p>
		<p><%= m.submit "Post" %></p>
	<% end %>

	<% if @feed_items %>
		<% @feed_items.each do |feed| %>
			<p><%= link_to feed.user.name, feed.user %><br>
				<%= feed.content %> | 
				<% if current_user.feed %>
					<%= link_to 'delete', feed, :method => :delete, :confirm => 'Are you sure?' %></p>
				<% end %>
		<% end %>
	<% end %>

<% else %>
	Generic Home page (you are not logged in)
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
      <h2>Form is invalid</h2>
      <ul><% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %></ul>
  <% end %>

  <p>Name<br><%= f.text_field :name %></p>
  <p>Email<br><%= f.text_field :email %></p>
  <p>Password<br><%= f.password_field :password %></p>
  <p>Password Confirmation<br><%= f.password_field :password_confirmation %></p>
  <p><%= f.submit "Update" %></p>

<% end %>

app/views/users/follow.html.erb
<% if @follow %><p>
	<% @follow.each do |x| %>
		<%= link_to x.name, user_path(x) %>
	</p><% end %>
<% else %>
	<p>No following/followers</p> 
<% end %>

app/views/users/index.html.erb
<%= will_paginate %>

<% @users.each do |user| %>
	<p>#<%= user.id %> | 
		<%= link_to user.name, user %> | 
		<%= link_to 'Delete', user_path(user.id) , :method => :delete, :confirm => 'Are you sure?' %>
	</p>
<% end %>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
      <h2>Form is invalid</h2>
      <ul><% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %></ul>
  <% end %>

  <p>Name<br><%= f.text_field :name %></p>
  <p>Email<br><%= f.text_field :email %></p>
  <p>Password<br><%= f.password_field :password %></p>
  <p>Password Confirmation<br><%= f.password_field :password_confirmation %></p>
  <p><%= f.submit "Create Account" %></p>

<% end %>

app/views/users/show.html.erb
<h1>Posts from <%= @user.name %></h1>
<% if current_user %>
	<% unless current_user == @user %>
		<% if current_user.following?(@user) %>
			<%= form_for current_user.relationships.find_by_followed_id(@user), :method => :delete do |f| %>
				<%= f.submit "Unfollow" %>
			<% end %>
		<% else %>
			<%= form_for current_user.relationships.build(:followed_id => @user.id) do |f| %>
				<%= f.hidden_field :followed_id %>
				<%= f.submit "Follow" %>
			<% end %>
		<% end %>
	<% end %>
<% end %>

<% if @user.microposts.any? %>
	<% @user.microposts.each do |m| %>
		<hr/><p><%= m.content %><br>Created At: <%= time_ago_in_words(m.created_at) %> ago. | 
				<% if current_user %>
					<%= link_to 'Delete', micropost_path(m), :method => :delete, :confirm => 'Are you sure?' %></p>
				<% end %>
			</p>
	<% end %>
<% end %>